# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/frmArkaPlan.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmArkaPlan(object):
    def setupUi(self, frmArkaPlan):
        frmArkaPlan.setObjectName("frmArkaPlan")
        frmArkaPlan.resize(1920, 1080)
        frmArkaPlan.setWindowTitle("")
        self.label = QtWidgets.QLabel(frmArkaPlan)
        self.label.setGeometry(QtCore.QRect(0, 0, 1921, 1081))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(frmArkaPlan)
        QtCore.QMetaObject.connectSlotsByName(frmArkaPlan)

    def retranslateUi(self, frmArkaPlan):
        pass
import ImageRestorant_rc
